concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}'
jobs:
  test:
    env:
      HOMEBREW_NO_REQUIRE_TAP_TRUST: '1'
    name: 'Tests'
    permissions:
      contents: write
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Configure
        run: >-
          cmake -G Xcode -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -B "${GITHUB_WORKSPACE}/build"
          --install-prefix "${GITHUB_WORKSPACE}/build/prefix" -DCMAKE_APPLE_SILICON_PROCESSOR=arm64
          -DBUILD_TESTS=ON -DCMAKE_OSX_SYSROOT=macosx
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Build
        run: cmake --build "${GITHUB_WORKSPACE}/build" --config "${BUILD_TYPE}" --verbose
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Run tests
        run: ctest -C "${BUILD_TYPE}" --output-on-failure --test-dir build/TorBrowserLauncherTests
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Generate coverage
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          xcrun llvm-profdata merge -sparse build/TorBrowserLauncherTests/default.profraw -o default.profdata
          xcrun llvm-cov export \
            "build/TorBrowserLauncherTests/${BUILD_TYPE}/TorBrowserLauncherTests.xctest/Contents/MacOS/TorBrowserLauncherTests" \
            --ignore-filename-regex='.*TorBrowserLauncherTests/.*' \
            -instr-profile=default.profdata -format=lcov > coverage.lcov
      - if: ${{ matrix.build-type == 'Debug' }}
        name: Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329
    strategy:
      matrix:
        build-type: [Debug, Release]
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions: {}
