jobs:
  test:
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    runs-on: 'macos-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          cmake -G Xcode -B build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
            --install-prefix ${{github.workspace}}/build/prefix \
            -DCMAKE_APPLE_SILICON_PROCESSOR=arm64 -DBUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config ${{matrix.build-type}} --verbose
      - name: Run tests
        run: ctest --output-on-failure -C ${{matrix.build-type}}
      # - if: ${{ matrix.build-type == 'Debug' }}
      #   name: Coveralls
      #   uses: coverallsapp/github-action@v2
    strategy:
      matrix:
        build-type: [Debug, Release]
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
