jobs:
  test:
    permissions:
      contents: write
    runs-on: 'macos-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure
        run: |
          cmake -G Xcode -B build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
            --install-prefix ${{github.workspace}}/build/prefix \
            -DCMAKE_APPLE_SILICON_PROCESSOR=arm64 -DBUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config ${{matrix.build-type}} --verbose
      - name: Run tests
        run: ctest --output-on-failure -C ${{matrix.build-type}} --test-dir build
      - name: Generate coverage
        if: ${{ matrix.build-type == 'Debug' }}
        run: |
          xcrun llvm-profdata merge -sparse \
            $(find build/TorBrowserLauncherTests -name "*.profraw") \
            -o default.profdata
          xcrun llvm-cov export \
            $(find build/TorBrowserLauncherTests -name "TorBrowserLauncherTests") \
            -instr-profile=default.profdata \
            -format=lcov > coverage.lcov
      - if: ${{ matrix.build-type == 'Debug' }}
        name: Coveralls
        uses: coverallsapp/github-action@v2
    strategy:
      matrix:
        build-type: [Debug, Release]
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
